export const PRODUCT_PACKAGE = 'PRODUCT_PACKAGE';
export const USER_PACKAGE = 'USER_PACKAGE';
export const INVENTORY_PACKAGE = 'INVENTORY_PACKAGE';

export const CART_PACKAGE = 'CART_PACKAGE';
export const ORDER_PACKAGE = 'ORDER_PACKAGE';
export const PAYMENT_PACKAGE = 'PAYMENT_PACKAGE';
export const NOTIFICATION_PACKAGE = 'NOTIFICATION_PACKAGE';
